ARCHITECTURE = avr
CORE = arduino
BOARD_TAG = uno
MONITOR_BAUDRATE = 115200

USER_LIB_PATH = ../../../

# Paths that repeat in all my arduino projects
include /home/doron/.arduino.mk

include /home/doron/repos/Arduino-Makefile/Arduino.mk
